#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------


# EXTENDED STEPS: delete all traces of possible previous runs
# remove all processors if present
rm -rf processor*
#------------------------------------------------------------------------------
